FROM nvcr.io/nvidia/pytorch:21.09-py3

RUN apt update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y python3-opencv

RUN mkdir -p /data
WORKDIR /data

RUN git clone https://github.com/ultralytics/yolov5 ./data

WORKDIR /data/yolov5/ 

CMD /bin/bash -c "jupyter lab --ip 0.0.0.0 --port 8888 --allow-root"