FROM nvcr.io/nvidia/l4t-ml:r32.6.1-py3

#ENV PYTHONUNBUFFERED=1

WORKDIR /app
#VOLUME /app/w251

RUN apt-get update
RUN apt install -y curl unzip
RUN python3 -m pip install pycocotools tqdm tensorboard tensorboardX pyyaml webcolors matplotlib
